### ISSUE TITLE
use  the customType.json of stafi to parse  AccountInfo error

### ISSUE THREAD

**Issue by raojianli** [stafiprotocol/rtoken-relay#1]
the stafi.json : https://github.com/stafiprotocol/rtoken-relay/blob/main/network/stafi.json

stafi-node: v0.5.0

 I use the scale.go to parse the  scale data https://github.com/itering/scale.go

I found  actually the free fee balance of accountInfo is an error, not  equal to the value of the chain

the code 

`
func (c *Client) decodeStorage(raw, objType string, metadataDecoder *scalecodec.MetadataDecoder, runtimeVersion *RuntimeVersion) ([]byte, error) {
	  option := types.ScaleDecoderOption{Metadata: &metadataDecoder.Metadata, Spec: runtimeVersion.SpecVersion}
	  m := types.ScaleDecoder{}
	  m.Init(types.ScaleBytes{Data: utiles.HexToBytes(raw)}, &option)
	  data := m.ProcessAndUpdateData(objType)
	  marshal, err := json.Marshal(data)
	  if err != nil {
		  return nil, err
	  }
	  return marshal, nil
}

res, err := c.decodeStorage(accountData, "AccountInfo<Index, AccountData>", metadataDecoder, runtimeVersion)
	if err != nil {
		return nil, err
	}
	accountInfo := &AccountInfo{}
	err = json.Unmarshal(res, accountInfo)
	if err != nil {
		return nil, err
	}

`

**Comment by Tore19** [comment]
As communicated before, just use the stafi.json file in this project directly
